-- ICONYCS Iron Gate audit table.
-- This table stores labels and salted hashes only. It does not store raw passcodes or raw IP addresses.

CREATE TABLE IF NOT EXISTS iconycs_gate_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  event_type TEXT NOT NULL CHECK (event_type IN ('attempt', 'entry', 'view', 'blocked', 'logout')),
  outcome TEXT NOT NULL CHECK (outcome IN ('success', 'failure', 'allowed', 'blocked')),
  status_code INTEGER NOT NULL,
  path TEXT,
  method TEXT,
  passcode_label TEXT,
  session_id TEXT,
  reason TEXT,
  ip_hash TEXT,
  user_agent_hash TEXT,
  city TEXT,
  region TEXT,
  referrer TEXT,
  country TEXT
);

ALTER TABLE iconycs_gate_audit
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS region TEXT,
  ADD COLUMN IF NOT EXISTS referrer TEXT;

CREATE INDEX IF NOT EXISTS iconycs_gate_audit_occurred_at_idx
  ON iconycs_gate_audit (occurred_at DESC);

CREATE INDEX IF NOT EXISTS iconycs_gate_audit_passcode_label_idx
  ON iconycs_gate_audit (passcode_label, occurred_at DESC);

ALTER TABLE iconycs_gate_audit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service role writes gate audit" ON iconycs_gate_audit;
CREATE POLICY "service role writes gate audit"
  ON iconycs_gate_audit
  FOR INSERT
  TO service_role
  WITH CHECK (true);

DROP POLICY IF EXISTS "service role reads gate audit" ON iconycs_gate_audit;
CREATE POLICY "service role reads gate audit"
  ON iconycs_gate_audit
  FOR SELECT
  TO service_role
  USING (true);
